/**
 * Strips raw persona header prefixes generated by LLMs (e.g. '[Aristotle (AI Thought Partner)]:', '[Aristotle]:', '**[Aristotle]**:')
 * to ensure message content renders cleanly inside UI persona cards without redundant header text.
 */
export function cleanSpeakerPrefix(text: string): string {
  if (!text) return '';
  return text
    .replace(/^(?:\[[^\]]+\]|\*\*\[[^\]]+\]\*\*|[\w\s]+\s*\([^)]*\)):\s*/i, '')
    .trim();
}
